# Generated by Django 5.0 on 2023-12-10 14:24

import car_collection_app.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Sports Car", "Sports Car"),
                            ("Pickup", "Pickup"),
                            ("Crossover", "Crossover"),
                            ("Minibus", "Minibus"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                (
                    "year",
                    models.IntegerField(
                        validators=[car_collection_app.web.validators.year_validator]
                    ),
                ),
                ("image_url", models.URLField()),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("age", models.IntegerField()),
                ("password", models.CharField(max_length=30)),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
                ("profile_picture", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
